---
sidebar: sidebar 
permalink: task-manage-private-google-cloud.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, google cloud 
summary: 'Gérez votre processus d"offre privée de bout en bout général et spécifique à Hyperscaler ainsi que vos guides d"acceptation et d"activation des services intelligents NetApp pour AWS, Azure et Google Cloud.' 
---
= Accepter et configurer une offre privée Google Cloud pour la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 


[role="lead"]
Acceptez une offre privée Marketplace pour la liste de la NetApp Console dans la console Google Cloud.  Configurez les informations d’identification Google Cloud dans la console.

.Avant de commencer
* Travaillez avec les ventes NetApp pour créer une offre privée. Votre équipe commerciale doit vous fournir le lien de l'offre.
* Votre compte de facturation ne doit pas être en essai gratuit. Les comptes d'essai gratuits ne peuvent pas accepter d'offres privées. Si vous tentez d’utiliser un compte de facturation d’essai, vous recevrez une erreur et aurez besoin de l’aide de l’équipe cloud NetApp .
* Les autorisations Google Cloud suivantes sont requises pour accepter l'offre :
+
** `roles/billing.admin`pour le compte de facturation Cloud ciblé ou l'organisation Google Cloud
** `roles/viewer`pour le projet facturé sur le compte de facturation Cloud






== Accepter l'offre privée dans Google Cloud

Un projet Google Cloud ne peut être associé qu'à un seul abonnement Marketplace. Si vous souhaitez utiliser deux abonnements différents pour les charges de travail dans le même projet Google Cloud, vous devez créer deux comptes de console distincts, un pour chaque abonnement.

[IMPORTANT]
====
Vous devez compléter toutes les étapes pour activer votre offre privée. Sauter des étapes peut entraîner des problèmes tels qu'une double charge.

Si vous constatez des divergences dans les conditions, les prix ou les détails de l’offre, ou si vous n’êtes pas sûr de l’offre à accepter, n’acceptez pas l’offre. Contactez votre équipe de compte NetApp pour obtenir des éclaircissements.

====
[NOTE]
====
Si vous disposez déjà d'un abonnement PAYGO actif ou d'une offre privée modifiée, il vous suffit d'effectuer les étapes d'acceptation. Dans ces cas, la Marketplace met à jour le plan dans la même liste et conserve le même ID d'abonnement, de sorte que l'association d'abonnement dans la console reste intacte.

====
.Étapes
. Cliquez sur le lien d’activation de l’offre privée fourni par votre équipe commerciale NetApp . Le lien devrait ressembler à ce qui suit :
`https://console.cloud.google.com/marketplace/private-offers/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee`
. Vous êtes redirigé vers Google Cloud Marketplace où vous pouvez consulter les détails de l'offre :
+
.. **Compte de facturation**
.. **Produit** : NetApp Console
.. **Détails de l'offre**
.. **Tarifs**
+
[NOTE]
====
Examinez attentivement les détails du plan, la durée et les prix. Si quelque chose est incorrect, n’acceptez pas l’offre. Contactez votre équipe de compte NetApp pour une modification.

====


. Confirmez que les informations sont exactes, acceptez les conditions et cliquez sur **Accepter**.
. Une icône de chargement apparaît lors de la création de l'abonnement.
. Une fois l'abonnement créé avec succès, une fenêtre contextuelle s'affiche : *Votre demande de commande a été envoyée à NetApp, Inc.*
. Cliquez sur **S'INSCRIRE AVEC NETAPP, Inc.**. Vous êtes redirigé vers la NetApp Console pour terminer la configuration de votre abonnement. Si l’offre privée a été acceptée par une autre personne de votre organisation :
+
.. Dans Google Cloud Marketplace, accédez à **Commandes**.
.. Localisez l'offre avec le statut **En attente**.
.. Cliquez sur le menu à trois points et sélectionnez **S'inscrire auprès de NetApp, Inc.**


. Vous êtes redirigé vers `https://console.netapp.com` et invité à se connecter.
. Après vous être connecté, vous êtes redirigé vers `https://console.netapp.com/licenses/overview` . Une fenêtre contextuelle s'affiche dans laquelle vous devez :
+
.. Saisissez un nom d'affichage pour l'*abonnement SaaS Marketplace*.
.. Sélectionnez les **Comptes** de la console qui doivent avoir accès à l’abonnement.
.. En option, vous pouvez activer **Remplacer l'abonnement existant** si vous souhaitez remplacer automatiquement un abonnement Marketplace existant dans un compte Console.
+
[NOTE]
====
*** Cette option de remplacement est limitée à un seul compte Console.
*** Si vous devez associer plusieurs comptes de console au même abonnement Marketplace, vous devez configurer les comptes supplémentaires manuellement.


====


. Cliquez sur **Devenir associé**.
. Remplissez le formulaire pour associer l'abonnement à votre organisation Console.  Ensuite, cliquez sur **Associer**.
. Après avoir associé l'abonnement, accédez à l'onglet **Préférences de facturation** et sélectionnez-le.
. Consultez les options d'abonnement disponibles sur la plateforme.
. Sélectionnez l'abonnement à la plateforme que vous souhaitez facturer.  Cela ne s'applique que lorsqu'il existe plus d'une option.
. Sélectionnez **Enregistrer les modifications**.
. Répétez ces étapes autant de fois que nécessaire, s'il existe plusieurs abonnements auprès de plusieurs hyperscalers.


Pour plus d'informations sur les abonnements à la plateforme et la facturation directe des licences, consultez la sectionlink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentation relative aux préférences de facturation"] .
