---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: Obtenez un aperçu de tous les abonnements et licences de votre organisation sur le tableau de bord de présentation de la console. 
---
= Utiliser l'aperçu du tableau de bord
:allow-uri-read: 




== Utiliser l'aperçu du tableau de bord

[role="lead"]
Le tableau de bord *Vue d'ensemble* dans la NetApp Console vous aide à surveiller l'état de vos Licenses and subscriptions afin de vous permettre de gérer les coûts et de maintenir le service lorsque les abonnements arrivent à expiration ou atteignent leurs limites de capacité.

Vous pouvez consulter les informations spécifiques relatives aux licenses and subscriptions de chacun de vos services de données (y compris Cloud Volumes ONTAP).

Le tableau de bord Licenses and subscriptions vous alerte des prochaines limites de capacité ou expirations, vous incitant à prendre les mesures nécessaires.



=== Afficher les détails d'un service de données spécifique

Le tableau de bord *Aperçu* fournit des informations détaillées sur les services suivants :

* Cloud Volumes ONTAP
* Reprise après sinistre
* Résilience aux ransomwares
* Sauvegarde et récupération
* Hiérarchisation du cloud


Par exemple, les administrateurs chargés de gérer les ressources Cloud Volumes ONTAP peuvent afficher la capacité actuelle de chaque licence ou abonnement, ce qui leur donne une vue ciblée des ressources relevant de leur compétence.


NOTE: Bien que vous puissiez mettre à jour et supprimer des licences depuis le tableau de bord, vous ne pouvez pas ajouter une nouvelle licence ou un nouvel abonnement.

link:task-manage-data-services-licenses.html["En savoir plus sur la gestion des licences"]. link:task-manage-subscriptions.html["En savoir plus sur la gestion des abonnements"].

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Administration > Licenses and subscriptions*.
. Sélectionnez *Aperçu*.
. Sélectionnez *Afficher* pour le service de données concerné (y compris Cloud Volumes ONTAP) pour afficher les détails et gérer les licences et les abonnements.
+
Chaque tuile fournit un aperçu graphique de la capacité.  Vous pouvez consulter la page de détails pour voir et gérer les méthodes de paiement pour cette capacité.

. Sélectionnez l'onglet *Licences* ou *Abonnements*.
. Filtrez le tableau en sélectionnant un filtre de colonne et une valeur à filtrer.  Par exemple, dans l’onglet *Abonnements*, vous pouvez filtrer la colonne Type par Contrat annuel ou Abonnement.
. Personnalisez les colonnes affichées dans le tableau.  Vous pouvez ajouter et supprimer des colonnes du tableau en sélectionnant l'icône *Colonne* pour indiquer les colonnes que vous souhaitez afficher ou masquer.
. Développez n’importe quelle ligne pour afficher les détails de ce que comprend l’abonnement ou la licence, la capacité achetée et les conditions.
. Utilisez le menu Actions pour gérer une licence ou un abonnement spécifique, comme la mise à jour d'une licence ou l'association d'un abonnement à une autre organisation.
+
Vous ne pouvez pas ajouter de nouvelles licences ou de nouveaux abonnements à partir de la page *Aperçu* pour un service spécifique.  Vous ne pouvez ajouter des licences ou des abonnements qu'à partir de l'onglet *Licences directes* ou de l'onglet *Abonnements Marketplace*, respectivement.

+
link:task-manage-data-services-licenses.html["En savoir plus sur la gestion des licences."] link:task-manage-subscriptions.html["En savoir plus sur la gestion des abonnements."]





=== Résoudre les problèmes de licence ou d'abonnement

Dans le tableau de bord Vue d'ensemble, vous pouvez consulter les problèmes de licenses and subscriptions à résoudre. Il s'agit notamment des licenses and subscriptions arrivant à expiration ou ayant atteint leur capacité maximale.

. Dans le menu de la NetApp Console , sélectionnez *Administration > Licenses and subscriptions*.
. Sélectionnez *Aperçu*.
. Dans la vignette *Action requise*, sélectionnez *Résoudre* pour afficher les problèmes à corriger. Si *Résoudre* n'apparaît pas, il n'y a aucun problème nécessitant une action.
. À partir de la page *Action requise*, sélectionnez l'onglet *Licences* ou l'onglet *Abonnements*.
. Utilisez le menu actions pour résoudre le problème.
+
link:task-manage-data-services-licenses.html["En savoir plus sur la gestion des licences"]. link:task-manage-subscriptions.html["En savoir plus sur la gestion des abonnements"].


